config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tours

  get ':category_id', to: 'tours#index', as: 'category_tours'

  root 'tours#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tour_categories
  has_many :tours, through: :tour_categories

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  has_many :tour_categories
  has_many :categories, through: :tour_categories

  validates :title, :teaser, :description, :category_ids, presence: true
  validates :url, format: %r|\Ahttp(s?)://www.google.com/maps|

end

app/models/tour_category.rb
class TourCategory < ActiveRecord::Base
  belongs_to :tour
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = if params[:category_id]
               Category.find(params[:category_id]).tours
             else
               Tour.all
             end
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tour
    @tour = Tour.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tour_params
    params.require(:tour).permit(:title, :teaser, :description, :url, category_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "LeezeMs" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<%= render partial: 'shared/navigation' %>

<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <h3>Sidebar</h3>
        <ul class="nav nav-list">
          <li class="nav-header">Sidebar</li>
          <li><%= link_to "Link1", "/path1" %></li>
          <li><%= link_to "Link2", "/path2" %></li>
          <li><%= link_to "Link3", "/path3" %></li>
        </ul>
      </div>
      <!--/.well -->
    </div>
    <!--/span-->
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; leeze.ms 2014</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">LeezeMs</a>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav pull-right">
        <% Category.all.each do |category| %>
            <li><%= link_to category.name, category_tours_path(category) %></li>
        <% end %>
        <% if current_user %>
            <li><%= link_to current_user.email, destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :teaser %><br>
    <%= f.text_field :teaser %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :categories %><br>
    <%= f.collection_select :category_ids, Category.all, :id, :name, { selected: @tour.categories.map(&:id), include_hidden: false},  multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/edit.html.erb
<h1>Editing tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<h1>All tours</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th colspan="4">Title</th>
  </tr>
  </thead>
  <tbody>
  <% @tours.each do |tour| %>
    <tr>
      <td><%= tour.title %></td>
      <td><%= link_to 'Show', tour %></td>
      <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
      <td><%= link_to 'Destroy', tour, prompt: 'Are you sure?' %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @tour.title %></h2>

<p>
  <%= @tour.teaser %>
</p>

<p>
  <iframe src="<%= @tour.url %>" frameborder="0" scrolling="no" width="1200" height="600" marginheight="0" marginwidth="0"></iframe>
</p>
<p>
  <%= @tour.description %>
</p>
<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>